'use client';

import dynamic from 'next/dynamic';
import HeroSection from '@/components/sections/HeroSection';

// Dynamic import for 3D components to avoid SSR issues
const SimWorldPreview = dynamic(() => import('@/components/world/SimWorldPreview'), {
  ssr: false,
  loading: () => (
    <div className="world-loading">
      <div className="loading-spinner"></div>
      <p>Loading SimWork World...</p>
    </div>
  )
});

export default function Home() {
  return (
    <main className="homepage">
      <HeroSection />

      <section className="world-preview-section">
        <div className="section-header">
          <h2>Experience the Future of Work</h2>
          <p>Step into our 2.5D open world and explore what makes SimWork revolutionary</p>
        </div>
        <SimWorldPreview />
      </section>

      <section className="features-section">
        <div className="container">
          <h2>Why SimWork?</h2>
          <div className="features-grid">
            <div className="feature-card">
              <div className="feature-icon">🎮</div>
              <h3>Immersive 2.5D World</h3>
              <p>Navigate a Ragnarok Online-inspired office environment with real workstations and interactive zones.</p>
              <a href="/live-preview" className="feature-link">Try Demo →</a>
            </div>
            <div className="feature-card">
              <div className="feature-icon">🛠️</div>
              <h3>Real Tools Embedded</h3>
              <p>Use actual development tools, design software, and project management interfaces within the game world.</p>
              <a href="/live-preview" className="feature-link">Explore Tools →</a>
            </div>
            <div className="feature-card">
              <div className="feature-icon">🎯</div>
              <h3>AI-Powered Quests</h3>
              <p>Complete realistic work tasks generated by AI that match your skill level and career goals.</p>
              <a href="/live-preview" className="feature-link">Start Quest →</a>
            </div>
            <div className="feature-card">
              <div className="feature-icon">👥</div>
              <h3>Freelancer Discovery</h3>
              <p>Connect with talented professionals and showcase your skills through completed quests and achievements.</p>
              <a href="/sign-up" className="feature-link">Join Now →</a>
            </div>
          </div>
        </div>
      </section>

      {/* Navigation Section */}
      <section className="navigation-section">
        <div className="container">
          <h2>Explore SimWork</h2>
          <div className="nav-grid">
            <a href="/live-preview" className="nav-card">
              <div className="nav-icon">🎮</div>
              <h3>Live Demo</h3>
              <p>Experience our 2.5D world and interactive workstations</p>
            </a>
            <a href="/pitch-deck" className="nav-card">
              <div className="nav-icon">📊</div>
              <h3>Pitch Deck</h3>
              <p>See our vision, market opportunity, and business model</p>
            </a>
            <a href="/why-us" className="nav-card">
              <div className="nav-icon">🏆</div>
              <h3>Why Us</h3>
              <p>Learn about our competitive advantages and team</p>
            </a>
            <a href="/roadmap" className="nav-card">
              <div className="nav-icon">🗺️</div>
              <h3>Roadmap</h3>
              <p>Follow our development journey and future plans</p>
            </a>
            <a href="/sign-up" className="nav-card">
              <div className="nav-icon">🚀</div>
              <h3>Get Started</h3>
              <p>Join our beta and be part of the future of work</p>
            </a>
          </div>
        </div>
      </section>
    </main>
  );
}
